### ISSUE TITLE
[Users table] City adherent is not present in the table in 'Зголошені' tab for the City admin 

### ISSUE THREAD

**Issue by NataliyaDominyuk** [ita-social-projects/EPlast#2660]
**Environment:** Mac OS Monterey 12.3.1, Google Chrome version 100.0.4896.127 (arm64)
**Reproducible:** always
**Build found:** 24cf084a98c3f4d2d216305b2d85fc8ea0b74ce2
**Priority:** high
**Severity:** medium

**Preconditions**
Sign in as city admin of Луцьк city (https://eplast.westeurope.cloudapp.azure.com/signin)

**Steps to reproduce**
1. Go to the left-side menu
2. Click on 'Довідник' -> 'Станиці'
3. Choose 'Луцьк'
4. Check 'Зголошені' section
5. Go to the left-side menu
6. Click on 'Довідник' -> 'Таблиця користувачів' 
7. Сheck 'Зголошені' tab

**Actual result**
City adherent is not present in 'Зголошені' tab for the City admin 

**Expected result**
City adherent should be present in 'Зголошені' tab of the users table for City admin 

![no user in зголошені](https://user-images.githubusercontent.com/104838173/179608696-68735f0a-340c-45e5-8594-ff9b5bb82a99.jpg)

**Comment by NataliyaDominyuk** [comment]
Deputy of the city admin gets 500 error on the user's table.

<img width="1438" alt="Screenshot 2022-09-06 at 17 01 16" src="https://user-images.githubusercontent.com/104838173/188655937-47031e81-2da8-47b9-a8ca-28278cb47410.png">

response logs:
System.AggregateException: One or more errors occurred. (Enumerator failed to MoveNextAsync.)
 ---> System.InvalidOperationException: Enumerator failed to MoveNextAsync.
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at EPlast.DataAccess.Repositories.RepositoryBase`1.GetFirstAsync(Expression`1 predicate, Func`2 include) in /EPlast/EPlast.DataAccess/Repositories/Realizations/Base/RepositoryBase.cs:line 84
   at EPlast.BLL.Services.AdminService.TableFilterParameters_byRole(IList`1 roles, String userId) in /EPlast/EPlast.BLL/Services/Admin/AdminService.cs:line 331
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at EPlast.BLL.Services.AdminService.GetUsersTableAsync(TableFilterParameters tableFilterParameters, String userId) in /EPlast/EPlast.BLL/Services/Admin/AdminService.cs:line 238
   at EPlast.WebApi.Controllers.AdminController.GetUsersTable(TableFilterParameters tableFilterParameters) in /EPlast/EPlast.WebApi/Controllers/AdminController.cs:line 332
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7,uk;q=0.6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoidnh3YnB6cGdoZ2ZkeWNtZG9sQG52aHJ3LmNvbSIsIm5hbWVpZCI6IjM3NTEzOTAyLTljYzgtNDkxNS1iYjJhLTQzMTMwMTU0MWNjNyIsImZhbWlseV9uYW1lIjoiMzc1MTM5MDItOWNjOC00OTE1LWJiMmEtNDMxMzAxNTQxY2M3IiwianRpIjoiNjZkNzc0ZjItNDAzNS00NjcyLWIzOTMtZTEyMGIwNTU5NWFmIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjpbItCT0L7Qu9C-0LLQsCDQmtGD0YDQtdC90Y8iLCLQlNGW0LvQvtCy0L7QtCDQmtC10YDRltCy0L3QvtCz0L4g0J7RgNCz0LDQvdGDIiwi0JfQsNGB0YLRg9C_0L3QuNC6INCT0L7Qu9C-0LLQuCDQodGC0LDQvdC40YbRliIsItCU0ZbQudGB0L3QuNC5INGH0LvQtdC9INC-0YDQs9Cw0L3RltC30LDRhtGW0ZciLCLQk9C-0LvQvtCy0LAg0J7QutGA0YPQs9C4Il0sImV4cCI6MTY2MjQ3OTM3MCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNTAvIiwiYXVkIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6MzAwMC8ifQ.HBfSibyMhyt0CUz27i1V8KH8t3eXuG_50cuDHG7pds8
Cookie: G_ENABLED_IDPS=google; fblo_392908158421729=y; .AspNetCore.Identity.Application=CfDJ8FoM11x3d-NKhfa6PfDiWWS3Ly8JtdXrGCYxPLxgz4bd1SsoKpz5TfXBeYAW7FY6_23rN1SOwoUGzKXXgpuc-RtrV9EzFkXtHxbXYSEjl12ShJsuiFURYxMdHoofoAv4grSS0Y5FOn8oI3BgZwkSXFzEY2VJ0jXziSeLtu2c-qxvM-oUpPweoHZq3xaNwVbunZM9231enva_l7Qfh1uI0tj1MuI5nTR7kqdikjR46f3rha0ZSvY4D2upYFLEiN3vq4M4i2QqOhP7fkYVyAPdJK7PH4gPhDvF5M1YmKBhbrIGJnkztgNXn679u0A_f_u_L8jbyvqmWteqm_ZeSWuOTRq2FHyg0ASTmR01zdIQXzXkOIu9uDKUCkRAhsWusvKEi9J-vezwKWOMVMOGT7elpT5T3JljpN9ToTQFmm3Tv9q_ikq2z-TgJIkxzM4lmX8gCHWw21Y0pl0qcUOyxCnK3kQmCl_PoY5QCzUu20X5Dmcb6uI0YuRLfr-7fEqik97N-lwppo-821hGysZIMSkqXUd7oKTr9LoSh-S2AwiYIVL436z69tdLNZW0N5MiYlXgUfJ1yslxRUjFsw5BW3IH_xf4YTW2r42UfnYTxQGwPlzjOg1Qgm1LepSvMRo7hDYGrF0F0h6K1Pt0GnsesQtzUaS6EdtrsQcYgGsqxVoZft79YjkXZ1SnP9JJ9B4igtjq_k7Yur6RXcBslLb-januZNhSibOtkEoU5svN-o0pC3kVPOwrwPeWMJB_D0qNjiOWrLZraZ29YuiZ-IxE7xW0eeG8AooGYtJr7GMevzpkbJoA3XKhT2nDiQETFJASf2VTBxlrR-UxXDQyqTr9CFvKiJhESv9wFBJhBCjDkT4OGMFxjhtPNWk0PFpG84H4ZHsF1Z-DsASb_YSYYnoMDNPzFCgQv6YVfm6HRxEc6w2B-y3y-YJlewkX1Ak7JXPRp3hrMVKtCTPDcTjHTuze88q2h-4oLjwK5sZdd_8X2MlaR2oaFt2tpIIJUGsmGxmtySWo-tPj8TrI9gQPc6SquABqfm07KaaV0l84s-ixDrdvIK1kVNug-OXQsHBp3bmExJjlzydqaeBcdSOTPuXwBV1S6dj9pMDupNFlVpq5iP7XLpOaGMpZWVtX5tUN6aVT0ZDSr-1fQoSEkiqsNikZtTSD0m-YxPZPyhc--zFW2JPCyDY1CMqKvPjTlUN8XZH2E4m_L32jVH0-45Tqazu_0XZy9oRiKobS_BlU8JRJ_4hmwq6IGKBdv13IsCRgnqvMkfg4SDNbKzdaWJWobiXJXu6nHYBdCxqUy4GclC33L02P8VRVHAQKFoBrcibenEDHt8f2tjgdGDg-_KjX_whmO0BwxeI
Host: eplast.westeurope.cloudapp.azure.com
Referer: https://eplast.westeurope.cloudapp.azure.com/user/table
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Mobile Safari/537.36
X-Request-ID: c0b934fc6a2812402bdb317700cad385
X-Real-IP: 45.12.25.13
X-Forwarded-For: 45.12.25.13
X-Forwarded-Host: eplast.westeurope.cloudapp.azure.com
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-Scheme: https
X-Scheme: https
sec-ch-ua: "Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"
sec-ch-ua-mobile: ?1
sec-ch-ua-platform: "Android"
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty
